### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Radiokot/ln-addr-to-invoice#3]
https://monitor.f-droid.org/builds/log/ua.com.radiokot.lnaddr2invoice/6#site-footer

so I edit the recipe
```
  - versionName: 1.3.0
    versionCode: 6
    commit: d57e52ed1ef83cbfe9065aa8c9fb072452bf1494
    subdir: app
    gradle:
      - yes
    srclibs:
      - reproducible-apk-tools@v0.2.3
    postbuild: $$reproducible-apk-tools$$/inplace-fix.py --zipalign fix-newlines $$OUT$$
      'META-INF/services/*' 'assets/app.properties' 'assets/open_source_licenses.html'
```

but
```
==== detail begin ====
verification of APK with copied signature failed
Comparing reference APK to APK with copied signature...
Unexpected diff output:
diff -r /tmp/tmpkcli_g2w/unsigned_binaries_ua.com.radiokot.lnaddr2invoice_6.binary/content/assets/open_source_licenses.html /tmp/tmpkcli_g2w/_tmp_tmpkcli_g2w_sigcp_ua.com.radiokot.lnaddr2invoice_6/content/assets/open_source_licenses.html
3c3
<     <style>body { font-size: 75%; font-size: 75%; font-size: 75%; font-size: 75%; font-size: 75%; font-family: sans-serif } pre { background-color: #eeeeee; padding: 1em; white-space: pre-wrap; display: inline-block }</style>
---
>     <style>body { font-size: 75%; font-size: 75%; font-size: 75%; font-size: 75%; font-size: 75%; font-size: 75%; font-size: 75%; font-size: 75%; font-family: sans-serif } pre { background-color: #eeeeee; padding: 1em; white-space: pre-wrap; display: inline-block }</style>
==== detail end ====
```

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/aae0f24f133e1d845d740c068b735903a104f30c
